theme="ayu_dark"
[editor]
bufferline="multiple"
completion-replace = true
end-of-line-diagnostics = "hint"
trim-trailing-whitespace = true


[editor.cursor-shape]
insert = "bar"
select = "underline"
[editor.lsp]
display-inlay-hints=true
[editor.statusline]
center = ["version-control"]
[editor.whitespace.render]
tab = "all"
newline = "all"
[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
