
[font]
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[window]
option_as_alt = "OnlyLeft"

[window.padding]
x = 6
y = 6

[general]
import = ["/Users/dario/.config/alacritty/themes/themes/tokyo-night.toml"]
